apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-server
  namespace: stable-diffusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download-server
  template:
    metadata:
      labels:
        app: download-server
    spec:
      containers:
      - name: download-server
        image: ghcr.io/bmrlab/stable-diffusion-webui/dl-server:{{ .Values.webui.images.downloadServer }}
        command:
        - /bin/sh
        args:
        - -c
        - uvicorn main:app --host 0.0.0.0 --reload --port 8000
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 32Gi
        volumeMounts:
        - mountPath: /app/data
          name: azure-file-data-root
          subPath: stable-diffusion-webui
      volumes:
      - name: azure-file-data-root
        persistentVolumeClaim:
          claimName: azure-file
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      nodeSelector:
        agentpool: gpupool1
        accelerator: nvidia
---
apiVersion: v1
kind: Service
metadata:
  name: download-server-svc
  namespace: stable-diffusion
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: download-server
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: download-server-ingress
  namespace: stable-diffusion
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "600"
spec:
  tls:
  - secretName: wildcard-webui-museai-cc
  rules:
  - host: dl.webui.museai.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: download-server-svc
            port:
              number: 8000
