apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file
  namespace: stable-diffusion
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
      storage: 1000Gi
