# config map for a yaml file
apiVersion: v1
kind: ConfigMap
metadata:
  name: webui-router-config
  namespace: stable-diffusion
data:
  config.yml: |-
    pool:
      res_origin_list:
  {{- range $i, $e := until (int .Values.webui.instances) }}
        - http://webui-svc-{{ $i }}:7860
  {{ end }}
      dl_server_origin:
        - http://download-server-svc:8000
      max_running_timeout: 600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-router
  namespace: stable-diffusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui-router
  template:
    metadata:
      labels:
        app: webui-router
    spec:
      containers:
      - name: webui-router
        image: ghcr.io/web3nomad/stable-diffusion-webui/webui-router:{{ .Values.webui.imageTagRouter }}
        command:
        - /bin/sh
        args:
        - -c
        - |
          echo '@app.get("/")' >> /app/main.py
          echo 'def ping():' >> /app/main.py
          echo '    return "success"' >> /app/main.py
          sed -i '245i\    return True' /app/app/core/pool.py
          uvicorn main:app --host 0.0.0.0 --reload --port 8000
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /app/data
          name: pvc-data-root
          subPath: stable-diffusion-webui
        - mountPath: /app/config.yml
          name: config
          subPath: config.yml
          readOnly: true
      volumes:
      - name: pvc-data-root
        persistentVolumeClaim:
          claimName: azure-managed-disk
      - configMap:
          defaultMode: 420
          name: webui-router-config
        name: config
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: webui-router-svc
  namespace: stable-diffusion
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: webui-router
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webui-router-ingress
  namespace: stable-diffusion
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "600"
spec:
  tls:
  - secretName: wildcard-webui-museai-cc
  rules:
  - host: router.webui.museai.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webui-router-svc
            port:
              number: 8000
