{{ range $i, $e := until (int .Values.webui.instances) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-{{ $i }}
  namespace: stable-diffusion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webui-{{ $i }}
  template:
    metadata:
      labels:
        app: webui-{{ $i }}
    spec:
      containers:
      - name: webui
        image: ghcr.io/web3nomad/stable-diffusion-webui:gpu-latest
        ports:
        - containerPort: 7860
        env:
        - name: CLI_ARGS
          value: --allow-code --medvram --xformers --enable-insecure-extension-access --api
        resources: {}
        # resources:
        #   requests:
        #     cpu: 1000m
        #     memory: 4Gi
        #     nvidia.com/gpu: "1"
        #   limits:
        #     cpu: 4000m
        #     memory: 16Gi
        #     nvidia.com/gpu: "1"
        volumeMounts:
        - mountPath: /data
          name: pvc-data-root
          subPath: stable-diffusion-webui
      volumes:
      - name: pvc-data-root
        persistentVolumeClaim:
          claimName: azure-managed-disk
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: webui-svc-{{ $i }}
  namespace: stable-diffusion
spec:
  ports:
  - port: 7860
    targetPort: 7860
  selector:
    app: webui-{{ $i }}
  type: ClusterIP
{{ end }}
