apiVersion: v1
kind: Namespace
metadata:
  name: testns
  labels:
    name: testns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: testns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test
        image: nginx:latest
        command: ["/bin/sh"]
        args: ["-c", "echo 'Hello from nginx-test' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-svc
  namespace: testns
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
  namespace: testns
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
spec:
  rules:
  - http:
      paths:
      - path: /test
        backend:
          service:
            name: nginx-test-svc
            port:
              number: 80
        pathType: Exact
