apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: download-job
  name: download-job
  namespace: stable-diffusion
spec:
  template:
    metadata:
      labels:
        app: download-job
    spec:
      containers:
      - name: download-script
        image: ghcr.io/web3nomad/stable-diffusion-webui/dl-script:5aab064
        volumeMounts:
        - mountPath: /data
          name: azure-file-data-root
          subPath: stable-diffusion-webui
      restartPolicy: OnFailure
      volumes:
      - name: azure-file-data-root
        persistentVolumeClaim:
          claimName: azure-file
      nodeSelector:
        agentpool: cpupool1
