name: File Download Script

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: setup versioning
      id: vars
      run: |
        build_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        build_version="$(git rev-parse --short HEAD)"
        echo "build_date=$build_date" >> $GITHUB_OUTPUT
        echo "build_version=$build_version" >> $GITHUB_OUTPUT

    - name: Build and push File Download Script
      uses: docker/build-push-action@v4
      with:
        context: ./services/download-script
        file: ./services/download-script/Dockerfile
        push: true
        tags: |
          ghcr.io/bmrlab/stable-diffusion-webui/dl-script:latest
          ghcr.io/bmrlab/stable-diffusion-webui/dl-script:${{ steps.vars.outputs.build_version }}
        platforms: linux/amd64
